<?xml version="1.0" encoding="utf-8"?>
<report
	progress="">
	<activity
		result="Failed"
		duration="682ms"
		durationms="682"
		type="root"
		rid="6319481ca1b4222"
		totalerrorcount="1"
		totalwarningcount="0"
		totalsuccesstestcasecount="0"
		totalfailedtestcasecount="0"
		totalblockedtestcasecount="0"
		childsuccesscount="0"
		childfailedcount="1"
		childblockedcount="0"
		totalsuccesscount="0"
		totalfailedcount="0"
		totalblockedcount="0"
		totalmaintenancemodecount="0"
		user="Administrator"
		rxversion="8.2.1.0"
		host="CIGNITI-W16"
		osversion="Microsoft Windows NT 6.2.9200.0 64bit"
		runtimeversion="4.0.30319.42000"
		procarch="32bit"
		oslanguage="en-US"
		dtnlanguage="en-US"
		screenresolution="1600x900"
		timestamp="5/24/2019 5:16:43 AM"
		timestampiso="2019-05-24T10:16:43"
		endtime="5/24/2019 5:16:45 AM"
		timeoutfactor="1">
		<detail>
			Ranorex Testscript
		</detail>
		<item
			timeRelativeToTestSuiteStartTime="00:00.681"
			timeRelativeToTestModuleStartTime="00:00.682"
			timeWallClock="05:16:44"
			time="00:00.681"
			level="Error"
			category="Module">
			<message>
				The test run has been aborted by the user.
			</message>
			<metainfo
				loglvl="Error">
			</metainfo>
		</item>
		<activity
			result="Failed"
			duration="0ms"
			durationms="0"
			type="test-suite"
			rid="268e4ba4fcab0898"
			totalerrorcount="0"
			totalwarningcount="0"
			totalsuccesstestcasecount="0"
			totalfailedtestcasecount="0"
			totalblockedtestcasecount="0"
			childsuccesscount="0"
			childfailedcount="0"
			childblockedcount="0"
			totalsuccesscount="0"
			totalfailedcount="0"
			totalblockedcount="0"
			totalmaintenancemodecount="0"
			testsuitename="AutomationSQLdm"
			headertext="AutomationSQLdm"
			runconfigname="TestRun"
			runlabel="">
			<params>
			</params>
			<detail>
				False
			</detail>
			<item
				timeRelativeToTestSuiteStartTime="00:01.793"
				timeRelativeToTestModuleStartTime="00:00.859"
				timeWallClock="05:16:45"
				time="00:01.793"
				level="Failure"
				category="TestSuite">
				<message>
					Thread was being aborted.
				</message>
				<metainfo
					stacktrace="   at Ranorex.Core.Reporting.ActivityStack.OnBeginActivity(Activity activity)&#13;&#10;   at Ranorex.Core.Reporting.ActivityStack.Begin(Activity activity)&#13;&#10;   at Ranorex.Core.Reporting.ActivityContext..ctor(Activity activity)&#13;&#10;   at Ranorex.Core.Reporting.ActivityContext.Begin(Activity activity)&#13;&#10;   at Ranorex.Core.Testing.TestSuite.Run(String runConfigName, String runLabel, Dictionary`2 parameters)&#13;&#10;   at Ranorex.Core.Testing.TestSuiteRunner.TryRunTestSuite(RunParams rp, TestSuite testSuite)&#13;&#10;   at Ranorex.Core.Testing.TestSuiteRunner.&lt;>c__DisplayClass13_1.&lt;RunInternal>b__5()&#13;&#10;   at Ranorex.Common.Types.OptCombinators.UnwrapOrElse[T](Opt`1 self, Func`1 generator)&#13;&#10;   at Ranorex.Core.Testing.TestSuiteRunner.RunInternal(Type containerType, String[] testSuiteXmls, RunParams[] rps)"
					loglvl="Failure">
				</metainfo>
			</item>
		</activity>
	</activity>
</report>
